# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ano_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='exe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prim10',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anuario',
            name='anuario',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='salones_curso',
            name='curso',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='salones_curso',
            name='salon',
            field=models.IntegerField(unique=True),
        ),
    ]
