# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ano_escolar', '0003_remove_alumno_anuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto_gde',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='foto_med',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='foto_peq',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
