# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ano_escolar', '0005_auto_20160106_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='anuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ano_escolar.Anuario'),
            preserve_default=False,
        ),
    ]
